// Code generated by ent, DO NOT EDIT.

package ent

import (
	"MwaiBanda/ent/article"
	"MwaiBanda/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ArticleUpdate is the builder for updating Article entities.
type ArticleUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleMutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdate) Where(ps ...predicate.Article) *ArticleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ArticleUpdate) SetName(v string) *ArticleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableName(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPublicationDate sets the "publicationDate" field.
func (_u *ArticleUpdate) SetPublicationDate(v string) *ArticleUpdate {
	_u.mutation.SetPublicationDate(v)
	return _u
}

// SetNillablePublicationDate sets the "publicationDate" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillablePublicationDate(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetPublicationDate(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ArticleUpdate) SetImage(v string) *ArticleUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableImage(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ArticleUpdate) SetSummary(v string) *ArticleUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableSummary(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *ArticleUpdate) SetBody(v string) *ArticleUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableBody(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ArticleUpdate) SetTags(v []string) *ArticleUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ArticleUpdate) AppendTags(v []string) *ArticleUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdate) Mutation() *ArticleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArticleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArticleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ArticleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(article.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicationDate(); ok {
		_spec.SetField(article.FieldPublicationDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(article.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(article.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(article.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(article.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldTags, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArticleUpdateOne is the builder for updating a single Article entity.
type ArticleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleMutation
}

// SetName sets the "name" field.
func (_u *ArticleUpdateOne) SetName(v string) *ArticleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableName(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPublicationDate sets the "publicationDate" field.
func (_u *ArticleUpdateOne) SetPublicationDate(v string) *ArticleUpdateOne {
	_u.mutation.SetPublicationDate(v)
	return _u
}

// SetNillablePublicationDate sets the "publicationDate" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillablePublicationDate(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetPublicationDate(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ArticleUpdateOne) SetImage(v string) *ArticleUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableImage(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ArticleUpdateOne) SetSummary(v string) *ArticleUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableSummary(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetBody sets the "body" field.
func (_u *ArticleUpdateOne) SetBody(v string) *ArticleUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableBody(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ArticleUpdateOne) SetTags(v []string) *ArticleUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ArticleUpdateOne) AppendTags(v []string) *ArticleUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdateOne) Mutation() *ArticleMutation {
	return _u.mutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdateOne) Where(ps ...predicate.Article) *ArticleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArticleUpdateOne) Select(field string, fields ...string) *ArticleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Article entity.
func (_u *ArticleUpdateOne) Save(ctx context.Context) (*Article, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdateOne) SaveX(ctx context.Context) *Article {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ArticleUpdateOne) sqlSave(ctx context.Context) (_node *Article, err error) {
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Article.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, article.FieldID)
		for _, f := range fields {
			if !article.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != article.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(article.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicationDate(); ok {
		_spec.SetField(article.FieldPublicationDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(article.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(article.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(article.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(article.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldTags, value)
		})
	}
	_node = &Article{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
