// Code generated by ent, DO NOT EDIT.

package ent

import (
	"MwaiBanda/ent/predicate"
	"MwaiBanda/ent/project"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ProjectUpdate is the builder for updating Project entities.
type ProjectUpdate struct {
	config
	hooks    []Hook
	mutation *ProjectMutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdate) Where(ps ...predicate.Project) *ProjectUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ProjectUpdate) SetName(v string) *ProjectUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableName(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStartDate sets the "startDate" field.
func (_u *ProjectUpdate) SetStartDate(v string) *ProjectUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "startDate" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableStartDate(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "endDate" field.
func (_u *ProjectUpdate) SetEndDate(v string) *ProjectUpdate {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "endDate" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableEndDate(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ProjectUpdate) SetImage(v string) *ProjectUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableImage(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ProjectUpdate) SetSummary(v string) *ProjectUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableSummary(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdate) SetDescription(v string) *ProjectUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableDescription(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetLink sets the "link" field.
func (_u *ProjectUpdate) SetLink(v string) *ProjectUpdate {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *ProjectUpdate) SetNillableLink(v *string) *ProjectUpdate {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ProjectUpdate) SetTags(v []string) *ProjectUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ProjectUpdate) AppendTags(v []string) *ProjectUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdate) Mutation() *ProjectMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProjectUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProjectUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProjectUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(project.FieldStartDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(project.FieldEndDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(project.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(project.FieldLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(project.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldTags, value)
		})
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProjectUpdateOne is the builder for updating a single Project entity.
type ProjectUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProjectMutation
}

// SetName sets the "name" field.
func (_u *ProjectUpdateOne) SetName(v string) *ProjectUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableName(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStartDate sets the "startDate" field.
func (_u *ProjectUpdateOne) SetStartDate(v string) *ProjectUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "startDate" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableStartDate(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetEndDate sets the "endDate" field.
func (_u *ProjectUpdateOne) SetEndDate(v string) *ProjectUpdateOne {
	_u.mutation.SetEndDate(v)
	return _u
}

// SetNillableEndDate sets the "endDate" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableEndDate(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetEndDate(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ProjectUpdateOne) SetImage(v string) *ProjectUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableImage(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *ProjectUpdateOne) SetSummary(v string) *ProjectUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableSummary(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ProjectUpdateOne) SetDescription(v string) *ProjectUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableDescription(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetLink sets the "link" field.
func (_u *ProjectUpdateOne) SetLink(v string) *ProjectUpdateOne {
	_u.mutation.SetLink(v)
	return _u
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (_u *ProjectUpdateOne) SetNillableLink(v *string) *ProjectUpdateOne {
	if v != nil {
		_u.SetLink(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *ProjectUpdateOne) SetTags(v []string) *ProjectUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *ProjectUpdateOne) AppendTags(v []string) *ProjectUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// Mutation returns the ProjectMutation object of the builder.
func (_u *ProjectUpdateOne) Mutation() *ProjectMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProjectUpdate builder.
func (_u *ProjectUpdateOne) Where(ps ...predicate.Project) *ProjectUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProjectUpdateOne) Select(field string, fields ...string) *ProjectUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Project entity.
func (_u *ProjectUpdateOne) Save(ctx context.Context) (*Project, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProjectUpdateOne) SaveX(ctx context.Context) *Project {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProjectUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProjectUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ProjectUpdateOne) sqlSave(ctx context.Context) (_node *Project, err error) {
	_spec := sqlgraph.NewUpdateSpec(project.Table, project.Columns, sqlgraph.NewFieldSpec(project.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Project.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, project.FieldID)
		for _, f := range fields {
			if !project.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != project.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(project.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(project.FieldStartDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.EndDate(); ok {
		_spec.SetField(project.FieldEndDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(project.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(project.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(project.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Link(); ok {
		_spec.SetField(project.FieldLink, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(project.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, project.FieldTags, value)
		})
	}
	_node = &Project{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{project.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
